// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.17;

library DataTypes {
    struct SellParams {
        // The identifier of a merchandise
        uint256 tokenId;
        // The cost of a merchandise
        uint256 price;
        // The sales amount
        uint16 amount;
        // The margin ratio that the seller needs to pay
        uint16 marginRate;
        // The fee ratio that the seller needs to pay
        uint16 feeRate;
        // The URL of the merchandise's information
        string newUri;
    }

    struct FeeInfo {
        uint256 rewarded;
        uint256 claimed;
    }

    struct UserInfo {
        uint16 marginRate;
        uint16 feeRate;
        uint8 rating;
    }

    struct MerchandiseInfo {
        uint256 price;
        address seller;
        uint256 margin;
    }

    struct Logistics {
        // The amount of the goods bought or returned
        uint16 amount;
        // Becomes the buyer when returned
        address seller;
        // Price at the time of purchase
        uint256 price;
        string logisticsNo;
        // Hash value of the delivery address generated by keccak256
        bytes32 deliveryAddress;
        // Block number when bought
        uint256 orderTime;
        // Block number when delivered
        uint256 completeTime;
        // Block number when returned
        uint256 returnTime;
    }
}
